<form class="form-panel" method="post" action="{{ $action }}">
    @csrf
    @if ($method !== 'POST') @method($method) @endif
    <div class="form-section-heading"><span class="form-step">01</span><div><h2>Visit details</h2><p>Identify the place, time, and person completing the check.</p></div></div>
    <div class="form-grid">
        <label class="form-field"><span>FACILITY <b>*</b></span><select name="facility_id" required><option value="">Choose a facility</option>@foreach ($facilities as $facility)<option value="{{ $facility->id }}" @selected((string) old('facility_id', $inspection?->facility_id ?? request('facility_id')) === (string) $facility->id)>{{ $facility->name }}{{ $facility->is_active ? '' : ' (inactive)' }}</option>@endforeach</select>@error('facility_id')<small class="field-error">{{ $message }}</small>@enderror</label>
        <label class="form-field"><span>INSPECTOR <b>*</b></span><input name="inspector" value="{{ old('inspector', $inspection?->inspector) }}" required maxlength="120" placeholder="Name">@error('inspector')<small class="field-error">{{ $message }}</small>@enderror</label>
        <label class="form-field"><span>DATE AND TIME <b>*</b></span><input type="datetime-local" name="inspected_at" value="{{ old('inspected_at', $inspection?->inspected_at?->format('Y-m-d\TH:i') ?? now()->format('Y-m-d\TH:i')) }}" required max="{{ now()->format('Y-m-d\TH:i') }}">@error('inspected_at')<small class="field-error">{{ $message }}</small>@enderror</label>
    </div>
    <div class="form-section-heading form-section-spaced"><span class="form-step">02</span><div><h2>Observed conditions</h2><p>Use the same scale each visit: 1 is poor, 5 is excellent.</p></div></div>
    <div class="form-grid">
        <label class="form-field"><span>CLEANLINESS SCORE <b>*</b></span><select name="cleanliness_score" required><option value="">Choose 1–5</option>@foreach (range(1, 5) as $score)<option value="{{ $score }}" @selected((string) old('cleanliness_score', $inspection?->cleanliness_score) === (string) $score)>{{ $score }}{{ $score === 1 ? ' · Poor' : ($score === 5 ? ' · Excellent' : '') }}</option>@endforeach</select>@error('cleanliness_score')<small class="field-error">{{ $message }}</small>@enderror</label>
        <label class="form-field"><span>ODOR SCORE <b>*</b></span><select name="odor_score" required><option value="">Choose 1–5</option>@foreach (range(1, 5) as $score)<option value="{{ $score }}" @selected((string) old('odor_score', $inspection?->odor_score) === (string) $score)>{{ $score }}{{ $score === 1 ? ' · Poor' : ($score === 5 ? ' · Excellent' : '') }}</option>@endforeach</select>@error('odor_score')<small class="field-error">{{ $message }}</small>@enderror</label>
        <label class="form-field"><span>WASTE LEVEL <b>*</b></span><select name="waste_level" required><option value="">Choose a level</option>@foreach (['low', 'moderate', 'high'] as $level)<option value="{{ $level }}" @selected(old('waste_level', $inspection?->waste_level) === $level)>{{ ucfirst($level) }}</option>@endforeach</select>@error('waste_level')<small class="field-error">{{ $message }}</small>@enderror</label>
        <label class="form-field"><span>WATER AVAILABLE <b>*</b></span><select name="water_available" required><option value="">Choose yes or no</option><option value="1" @selected((string) old('water_available', isset($inspection) ? (int) $inspection->water_available : '') === '1')>Yes</option><option value="0" @selected((string) old('water_available', isset($inspection) ? (int) $inspection->water_available : '') === '0')>No</option></select>@error('water_available')<small class="field-error">{{ $message }}</small>@enderror</label>
        <label class="form-field"><span>FOOTFALL <b>*</b></span><input type="number" name="footfall" value="{{ old('footfall', $inspection?->footfall ?? 0) }}" required min="0" max="10000000">@error('footfall')<small class="field-error">{{ $message }}</small>@enderror</label>
        <label class="form-field"><span>COMPLAINTS <b>*</b></span><input type="number" name="complaints" value="{{ old('complaints', $inspection?->complaints ?? 0) }}" required min="0" max="1000000">@error('complaints')<small class="field-error">{{ $message }}</small>@enderror</label>
        <label class="form-field"><span>HOURS SINCE CLEANING <b>*</b></span><input type="number" name="hours_since_cleaning" value="{{ old('hours_since_cleaning', $inspection?->hours_since_cleaning ?? 0) }}" required min="0" max="8760">@error('hours_since_cleaning')<small class="field-error">{{ $message }}</small>@enderror</label>
    </div>
    <div class="form-actions"><a class="text-link" href="{{ route('inspections.index') }}">Discard</a><button class="button button-dark" type="submit">Save inspection <span>↗</span></button></div>
</form>